#!/usr/bin/python

import sys
import re
import pprint
import time
import os
import multiprocessing
from xml.etree import ElementTree

def key_vm_discovery(arg):
    vm_list = [v for v in os.listdir("/etc/vservers/") if not v.startswith(".")]

    return pprint.pformat({'data': [{"{#VMNAME}" : t} for t in vm_list]}).replace("'", '"')

def key_vm_status(arg):
    stateNames = [ "running",
                   "shut off"]
    state = 1
    if os.path.isfile("/etc/vservers/%s/run" % arg):
      state = 0
    return stateNames[state]


def key_vm_net_in(arg):
    result = 0
    if os.path.isfile("/etc/vservers/%s/run" % arg):
        id = int(open("/etc/vservers/%s/run" % arg).read())
        lines = open("/proc/virtual/%d/cacct" % id).read()
        inet_line = [l for l in lines.splitlines() if l.startswith("INET:")][0]
        received = inet_line.split("\t")[1].strip()
        result = received.split("/")[1]
    return result
    
def key_vm_net_out(arg):
    result = 0
    if os.path.isfile("/etc/vservers/%s/run" % arg):
        id = int(open("/etc/vservers/%s/run" % arg).read())
        lines = open("/proc/virtual/%d/cacct" % id).read()
        inet_line = [l for l in lines.splitlines() if l.startswith("INET:")][0]
        sent = inet_line.split("\t")[2].strip()
        result = sent.split("/")[1]
    return result

def key_vm_cputime(arg):
    cfg = '/dev/cgroup/%s/cpuacct.usage' % arg
    if os.path.isfile(cfg):
        cputime = long(open(cfg, 'r').read())
        return float(cputime) / 1000000000
    return ''

def key_vm_cputime_system(arg):
    cputime = key_vm_cputime(arg)
    if cputime != '':
        cpunum = multiprocessing.cpu_count()
        return cputime / cpunum
    return ''

def key_vm_memory(arg):
    cfg = '/dev/cgroup/%s/memory.usage_in_bytes' % arg
    if os.path.isfile(cfg):
        memory = long(open(cfg, 'r').read())
        return memory
    return ''

def key_vm_memory_max(arg):
    cfg = '/dev/cgroup/%s/memory.limit_in_bytes' % arg
    if os.path.isfile(cfg):
        memory_max = long(open(cfg, 'r').read())
        return memory_max
    return ''

def key_vm_memory_percent(arg):
    memory_max = key_vm_memory_max(arg)
    memory = key_vm_memory(arg)
    if memory != '':
        return float(memory) / memory_max;
    return ''

def key_vm_disk_usage(arg):
    r = os.popen("vdlimit --xid '%s' /vservers/" % arg).read()
    for l in r.splitlines():
        if l.startswith("space_used="):
            return long(l[11:]) * 1024
    return ''

def key_vm_uptime(arg):
    return 0

def main(argv):

    command = None
    if len(argv) > 1:
        command = argv[1]
        
    if command == None or not re.match("^[a-zA-Z1-9_i\.]+$", command):
        print 'invalid data key: ' + str(command)
        sys.exit(1)

    argument = None
    if len(argv) > 2:
        argument = argv[2]
        if len(argument) == 0 or argument[0] == '_':
            argument = None
        if argument is not None and not re.match("^[\ a-zA-Z1-9_i\./]+$", argument):
            print 'invalid argument: ' + argument
            sys.exit(1)

    command = command.replace('.', '_')
    func = "key_%s" % command

    if not func in globals():
        print 'could not find function: ' + func
        sys.exit(1)

    result = globals()[func](argument)
    print result

if __name__ == "__main__":
    try:
        main(sys.argv)
    except KeyboardInterrupt:
        pass
